/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["address.index"];
        put?: never;
        post: operations["address.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/addresses/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["address.destroy"];
        options?: never;
        head?: never;
        patch: operations["address.update"];
        trace?: never;
    };
    "/v1/central/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["central.auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["central.auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tenant.auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tenant.auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.passwordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/billing/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["billing.subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["billing.webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["brand.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cart.show"];
        put?: never;
        post?: never;
        delete: operations["cart.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cart.addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cart.removeItem"];
        options?: never;
        head?: never;
        patch: operations["cart.updateItem"];
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["category.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkout/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout.createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkout/session/{session}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["checkout.updateSession"];
        trace?: never;
    };
    "/v1/checkout/session/{session}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout.complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["customerAuth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["customerAuth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["customerAuth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["customerAuth.passwordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customerProfile.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["customerProfile.update"];
        trace?: never;
    };
    "/v1/inventory/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["inventory.update"];
        trace?: never;
    };
    "/v1/central/platform/moderation-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["moderation.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/platform/moderation-queue/{flag}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moderation.action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/newsletter/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["newsletter.subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/newsletter/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["newsletter.unsubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{order}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order.tracking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["plan.index"];
        put?: never;
        post: operations["plan.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/plans/{plan}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["plan.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/platform/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["platformSetting.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["platformSetting.update"];
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product.index"];
        put?: never;
        post: operations["product.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product.show"];
        put: operations["product.update"];
        post?: never;
        delete: operations["product.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public — approved reviews only. A submitted review starts 'pending'
         *     (see store()) and only ever becomes visible here once a platform
         *     moderator actions its ModerationFlag to 'approved'; 'pending' and
         *     'rejected' reviews never appear in this listing
         */
        get: operations["review.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seller/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sellerAnalytics.summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seller/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sellerOrder.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seller/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sellerOrder.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seller/orders/{order}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["sellerOrder.updateStatus"];
        trace?: never;
    };
    "/v1/central/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup.signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/onboarding/{tenant}/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup.theme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/onboarding/{tenant}/go-live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup.goLive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tenantManagement.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/central/tenants/{tenant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tenantManagement.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tenantManagement.update"];
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tenantSettings.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tenantSettings.update"];
        trace?: never;
    };
    "/v1/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wishlist.index"];
        put?: never;
        post: operations["wishlist.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wishlist/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["wishlist.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Address */
        Address: string[];
        /** Brand */
        Brand: string[];
        /** CartItem */
        CartItem: string[];
        /** CheckoutSession */
        CheckoutSession: string[];
        /** InventoryLevel */
        InventoryLevel: string[];
        /** ModerationFlag */
        ModerationFlag: {
            id: number;
            flaggable_type: string;
            flaggable_id: string;
            tenant_id: string | null;
            reason: string;
            status: string;
            source: string;
            actioned_by: number | null;
            /** Format: date-time */
            actioned_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** NewsletterSubscriber */
        NewsletterSubscriber: string[];
        /** Order */
        Order: string[];
        /** OrderStatusHistory */
        OrderStatusHistory: string[];
        /** Plan */
        Plan: {
            id: number;
            name: string;
            slug: string;
            price_cents: number;
            currency: string;
            billing_interval: string;
            product_limit: number | null;
            staff_limit: number | null;
            feature_flags: unknown[] | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** Review */
        Review: string[];
        /** Shipment */
        Shipment: string[];
        /** Tenant */
        Tenant: {
            id: string;
            name: string;
            status: string;
            branding_logo_url: string | null;
            branding_theme: string;
            branding_primary_color: string | null;
            default_locale: string;
            default_currency: string;
            trial_ends_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            data: unknown[] | null;
        };
        /** Wishlist */
        Wishlist: string[];
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "address.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "address.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "address.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The address ID */
                address: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "address.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The address ID */
                address: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "central.auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        admin: {
                            id: number;
                            name: string;
                            email: string;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "central.auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logged out.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        email: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tenant.auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        user: unknown[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "tenant.auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logged out.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /**
             * @description In production this is emailed to the invitee, never returned in
             *     the response body — surfaced here only so the endpoint contract
             *     is testable without a mail transport wired up yet.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: unknown[];
                        setup_token: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example Only the store owner can invite staff.
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.passwordReset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Password updated.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "billing.subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tenant_id: string;
                    plan_id: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        checkout_url: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "billing.webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: boolean;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Invalid webhook signature.";
                    };
                };
            };
        };
    };
    "brand.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Brand"][];
                    };
                };
            };
        };
    };
    "cart.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        guest_token: string;
                        currency: string;
                        items: components["schemas"]["CartItem"][];
                        subtotal_minor: number;
                    } | {
                        items: string[];
                        subtotal_minor: number;
                    };
                };
            };
        };
    };
    "cart.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Cart cleared.";
                    };
                };
            };
        };
    };
    "cart.addItem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    product_variant_id: number;
                    quantity: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        guest_token: string;
                        currency: string;
                        items: components["schemas"]["CartItem"][];
                        subtotal_minor: number;
                    } | {
                        items: string[];
                        subtotal_minor: number;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cart.removeItem": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        guest_token: string;
                        currency: string;
                        items: components["schemas"]["CartItem"][];
                        subtotal_minor: number;
                    } | {
                        items: string[];
                        subtotal_minor: number;
                    };
                };
            };
        };
    };
    "cart.updateItem": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    quantity: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        guest_token: string;
                        currency: string;
                        items: components["schemas"]["CartItem"][];
                        subtotal_minor: number;
                    } | {
                        items: string[];
                        subtotal_minor: number;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "category.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            parent_id: string;
                            slug: string;
                            image_url: string;
                            name: string | null;
                            description: string | null;
                        }[];
                        locale: string;
                    };
                };
            };
        };
    };
    "checkout.createSession": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cart_id: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "checkout.updateSession": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status?: "address" | "shipping" | "payment" | "complete";
                    shipping_address_id?: number;
                    shipping_method?: string;
                    payment_method?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "checkout.complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session ID */
                session: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Cart is empty.";
                    };
                };
            };
        };
    };
    "customerAuth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @enum {string|null} */
                    preferred_locale?: "en" | "ar" | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        customer: unknown[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "customerAuth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        customer: unknown[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "customerAuth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logged out.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "customerAuth.passwordReset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Password updated.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "customerProfile.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "customerProfile.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    phone?: string | null;
                    /** @enum {string} */
                    preferred_locale?: "en" | "ar";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "inventory.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The variant ID */
                variant: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    quantity_available: number;
                    quantity_reserved?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryLevel"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "moderation.index": {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_page: number;
                        data: components["schemas"]["ModerationFlag"][];
                        first_page_url: string | null;
                        from: number | null;
                        last_page_url: string | null;
                        last_page: number;
                        /** @description Generated paginator links. */
                        links: {
                            url: string | null;
                            label: string;
                            active: boolean;
                        }[];
                        next_page_url: string | null;
                        /** @description Base path for paginator generated URLs. */
                        path: string | null;
                        /** @description Number of items shown per page. */
                        per_page: number;
                        prev_page_url: string | null;
                        /** @description Number of the last item in the slice. */
                        to: number | null;
                        /** @description Total number of items being paginated. */
                        total: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "moderation.action": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The flag ID */
                flag: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "actioned" | "dismissed";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationFlag"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "newsletter.subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsletterSubscriber"];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "newsletter.unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Unsubscribed.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "order.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_page: number;
                        data: components["schemas"]["Order"][];
                        first_page_url: string | null;
                        from: number | null;
                        last_page_url: string | null;
                        last_page: number;
                        /** @description Generated paginator links. */
                        links: {
                            url: string | null;
                            label: string;
                            active: boolean;
                        }[];
                        next_page_url: string | null;
                        /** @description Base path for paginator generated URLs. */
                        path: string | null;
                        /** @description Number of items shown per page. */
                        per_page: number;
                        prev_page_url: string | null;
                        /** @description Number of the last item in the slice. */
                        to: number | null;
                        /** @description Total number of items being paginated. */
                        total: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "order.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "order.tracking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order_number: string;
                        status: string;
                        history: components["schemas"]["OrderStatusHistory"][];
                        shipment: components["schemas"]["Shipment"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "plan.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "plan.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    price_cents: number;
                    currency: string;
                    /** @enum {string} */
                    billing_interval: "month" | "year";
                    product_limit?: number | null;
                    staff_limit?: number | null;
                    feature_flags?: string[] | null;
                    is_active?: boolean;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "plan.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The plan ID */
                plan: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    price_cents?: number;
                    currency?: string;
                    /** @enum {string} */
                    billing_interval?: "month" | "year";
                    product_limit?: number | null;
                    staff_limit?: number | null;
                    feature_flags?: string[] | null;
                    is_active?: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "platformSetting.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "platformSetting.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    settings: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "product.index": {
        parameters: {
            query?: {
                currency?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            sku: string;
                            slug: string;
                            status: string;
                            is_featured: string;
                            locale: string;
                            name: string | null;
                            description: string | null;
                            category_id: string;
                            brand_id: string;
                            image_url: string | null;
                            price: {
                                currency: string | null;
                                amount_minor: string | null;
                                formatted: string;
                            } | null;
                            discount_badge: string;
                            variants: {
                                id: string;
                                sku: string;
                                attributes: string;
                                image_url: string;
                                is_default: string;
                                in_stock: boolean;
                                price: string;
                            }[];
                        }[];
                        meta: {
                            current_page: number;
                            last_page: number;
                            total: number;
                        };
                        locale: string;
                        currency: string | unknown[] | null;
                    };
                };
            };
        };
    };
    "product.store": {
        parameters: {
            query?: {
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sku: string;
                    slug: string;
                    category_id?: number | null;
                    brand_id?: number | null;
                    /** @enum {string} */
                    status?: "draft" | "active" | "archived";
                    is_featured?: boolean;
                    translations: {
                        locale: string;
                        name: string;
                        description?: string | null;
                    }[];
                    variants: {
                        sku: string;
                        attributes?: string[] | null;
                        /** Format: uri */
                        image_url?: string | null;
                        is_default?: boolean;
                        prices: {
                            currency: string;
                            amount_minor: number;
                        }[];
                        inventory?: {
                            quantity_available?: number;
                        };
                    }[];
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        sku: string;
                        slug: string;
                        status: string;
                        is_featured: string;
                        locale: string;
                        name: string | null;
                        description: string | null;
                        category_id: string;
                        brand_id: string;
                        image_url: string | null;
                        price: {
                            currency: string | null;
                            amount_minor: string | null;
                            formatted: string;
                        } | null;
                        discount_badge: string;
                        variants: {
                            id: string;
                            sku: string;
                            attributes: string;
                            image_url: string;
                            is_default: string;
                            in_stock: boolean;
                            price: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "product.show": {
        parameters: {
            query?: {
                currency?: string;
            };
            header?: never;
            path: {
                /** @description The product ID */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        sku: string;
                        slug: string;
                        status: string;
                        is_featured: string;
                        locale: string;
                        name: string | null;
                        description: string | null;
                        category_id: string;
                        brand_id: string;
                        image_url: string | null;
                        price: {
                            currency: string | null;
                            amount_minor: string | null;
                            formatted: string;
                        } | null;
                        discount_badge: string;
                        variants: {
                            id: string;
                            sku: string;
                            attributes: string;
                            image_url: string;
                            is_default: string;
                            in_stock: boolean;
                            price: string;
                        }[];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "product.update": {
        parameters: {
            query?: {
                currency?: string;
            };
            header?: never;
            path: {
                /** @description The product ID */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    sku?: string;
                    slug?: string;
                    category_id?: number | null;
                    brand_id?: number | null;
                    /** @enum {string} */
                    status?: "draft" | "active" | "archived";
                    is_featured?: boolean;
                    translations?: {
                        locale?: string;
                        name?: string;
                        description?: string | null;
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        sku: string;
                        slug: string;
                        status: string;
                        is_featured: string;
                        locale: string;
                        name: string | null;
                        description: string | null;
                        category_id: string;
                        brand_id: string;
                        image_url: string | null;
                        price: {
                            currency: string | null;
                            amount_minor: string | null;
                            formatted: string;
                        } | null;
                        discount_badge: string;
                        variants: {
                            id: string;
                            sku: string;
                            attributes: string;
                            image_url: string;
                            is_default: string;
                            in_stock: boolean;
                            price: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "product.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product ID */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "review.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product ID */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_page: number;
                        data: components["schemas"]["Review"][];
                        first_page_url: string | null;
                        from: number | null;
                        last_page_url: string | null;
                        last_page: number;
                        /** @description Generated paginator links. */
                        links: {
                            url: string | null;
                            label: string;
                            active: boolean;
                        }[];
                        next_page_url: string | null;
                        /** @description Base path for paginator generated URLs. */
                        path: string | null;
                        /** @description Number of items shown per page. */
                        per_page: number;
                        prev_page_url: string | null;
                        /** @description Number of the last item in the slice. */
                        to: number | null;
                        /** @description Total number of items being paginated. */
                        total: number;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "review.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    product_id: number;
                    rating: number;
                    title?: string | null;
                    body?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "search.index": {
        parameters: {
            query: {
                q: string;
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            sku: string;
                            slug: string;
                            status: string;
                            is_featured: string;
                            locale: string;
                            name: string | null;
                            description: string | null;
                            category_id: string;
                            brand_id: string;
                            image_url: string | null;
                            price: {
                                currency: string | null;
                                amount_minor: string | null;
                                formatted: string;
                            } | null;
                            discount_badge: string;
                            variants: {
                                id: string;
                                sku: string;
                                attributes: string;
                                image_url: string;
                                is_default: string;
                                in_stock: boolean;
                                price: string;
                            }[];
                        }[];
                        meta: {
                            current_page: number;
                            last_page: number;
                            total: number;
                        };
                        query: string | unknown[] | null;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "sellerAnalytics.summary": {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        period: {
                            from: string;
                            to: string;
                        };
                        revenue_by_currency: string;
                        orders_count: string;
                        top_products: {
                            product_variant_id: string;
                            product_name: string;
                            quantity_sold: number;
                            revenue_minor: number;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "sellerOrder.index": {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_page: number;
                        data: components["schemas"]["Order"][];
                        first_page_url: string | null;
                        from: number | null;
                        last_page_url: string | null;
                        last_page: number;
                        /** @description Generated paginator links. */
                        links: {
                            url: string | null;
                            label: string;
                            active: boolean;
                        }[];
                        next_page_url: string | null;
                        /** @description Base path for paginator generated URLs. */
                        path: string | null;
                        /** @description Number of items shown per page. */
                        per_page: number;
                        prev_page_url: string | null;
                        /** @description Number of the last item in the slice. */
                        to: number | null;
                        /** @description Total number of items being paginated. */
                        total: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "sellerOrder.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "sellerOrder.updateStatus": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Matches the `status` column comment on the orders migration.
                     * @enum {string}
                     */
                    status: "pending" | "paid" | "fulfilled" | "cancelled" | "refunded";
                    note?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"] | null;
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "signup.signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    business_name: string;
                    subdomain: string;
                    admin_name: string;
                    /** Format: email */
                    admin_email: string;
                    admin_password: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tenant_id: string;
                        domain: string;
                        status: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "signup.theme": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    template_id?: string | null;
                    business_description?: string | null;
                    primary_color?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tenant_id: string;
                        branding_theme: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "signup.goLive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tenant_id: string;
                        status: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Add at least one product before going live.";
                    };
                };
            };
        };
    };
    "tenantManagement.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_page: number;
                        data: components["schemas"]["Tenant"][];
                        first_page_url: string | null;
                        from: number | null;
                        last_page_url: string | null;
                        last_page: number;
                        /** @description Generated paginator links. */
                        links: {
                            url: string | null;
                            label: string;
                            active: boolean;
                        }[];
                        next_page_url: string | null;
                        /** @description Base path for paginator generated URLs. */
                        path: string | null;
                        /** @description Number of items shown per page. */
                        per_page: number;
                        prev_page_url: string | null;
                        /** @description Number of the last item in the slice. */
                        to: number | null;
                        /** @description Total number of items being paginated. */
                        total: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tenantManagement.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tenantManagement.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 'pending' is set by signup/onboarding itself, not by this
                     *     endpoint — a super-admin only ever activates or suspends.
                     * @enum {string}
                     */
                    status: "active" | "suspended";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "tenantSettings.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: unknown;
                        branding: {
                            logo_url: unknown;
                            theme: unknown;
                            primary_color: unknown;
                        };
                        default_locale: unknown;
                        default_currency: unknown;
                    };
                };
            };
        };
    };
    "tenantSettings.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    branding?: {
                        logo_url?: string | null;
                        theme?: string | null;
                        primary_color?: string | null;
                    };
                    default_locale?: string;
                    default_currency?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: unknown;
                        branding: {
                            logo_url: unknown;
                            theme: unknown;
                            primary_color: unknown;
                        };
                        default_locale: unknown;
                        default_currency: unknown;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example Only the store owner can update settings.
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "wishlist.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wishlist"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "wishlist.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    product_variant_id: number;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wishlist"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "wishlist.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Removed.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
}
